services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: ugram-postgres
    shm_size: 128mb
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ugram-database:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - ugram-network

  backend:
    depends_on:
      - postgres
    image: ugram-backend
    build:
      context: ../../
      dockerfile: ./packages/backend/Dockerfile
    container_name: ugram-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.prod

    networks:
      - ugram-network
    restart: unless-stopped

networks:
  ugram-network:

volumes:
  ugram-database:
